baseURL = "https://pan1018.github.io/my-hugo-site/"
languageCode = "en-us"
title = "Yuyang Pan"
theme = "PaperMod"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 3


[params]
  homeInfoParams = { 
    Title = "👋 Hi, I'm Yuyang Pan", 
    Content = "Welcome to my personal Hugo website. Explore my [posts](/posts/) or read more [about me](/about/)." 
  }

