baseURL = 'https://<pan1018>.github.io/my-hugo-site/'
languageCode = 'en-us'
title = 'Yuyang Pan'
theme = "PaperMod"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

